name: GitHub Pages
on: workflow_dispatch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "steven23851/test"

      - uses: actions/configure-pages@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Docutils
        run: pip install docutils pygments

      - name: rst2html using Docutils
        working-directory: ./docs/
        run: |
          while read -r RST
          do
            HTML="${RST%.rst}.html"
            python -m docutils --writer=html5 --output="$HTML" -- "$RST"
            sed -i '/<\/head>/i <script src="info.js"></script>' -- "$HTML"
          done < <(find . -type f -name "*.rst")

      - name: Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs/
          destination: ./_site/

      - uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
